### ISSUE TITLE
v0.2.9 is a branch and a tag

### ISSUE THREAD

**Issue by DanNixon** [joshrotenberg/adrs#38]
There is both a branch and a tag named `v0.2.9`.
In nixpkgs, this make it impossible to download the source archive for the tag via [`fetchFromGithub`](https://ryantm.github.io/nixpkgs/builders/fetchers/#fetchfromgithub).

Could the branch be renamed or removed?

**Comment by joshrotenberg** [comment]
Deleted,

**Comment by DanNixon** [comment]
:+1:
